# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'admin_group_relation',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('join_group_setting', models.IntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('admin', models.ManyToManyField(related_name='managed_groups', through='group.AdminGroupRelation', to='authentication.MyUser')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_groups', to='authentication.MyUser')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='JoinGroupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_join_group_requests', to='authentication.MyUser')),
            ],
            options={
                'db_table': 'join_group_request',
            },
        ),
        migrations.CreateModel(
            name='UserGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.MyUser')),
            ],
            options={
                'db_table': 'user_group_relation',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='group.UserGroupRelation', to='authentication.MyUser'),
        ),
        migrations.AddField(
            model_name='admingrouprelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
        migrations.AddField(
            model_name='admingrouprelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.MyUser'),
        ),
        migrations.AlterUniqueTogether(
            name='usergrouprelation',
            unique_together=set([('group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='admingrouprelation',
            unique_together=set([('user', 'group')]),
        ),
    ]
