# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeOJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max_instance_number', models.IntegerField()),
                ('used_instance_number', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'JudgeOJ',
            },
        ),
        migrations.CreateModel(
            name='JudgeWaitingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=40)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'judge_waiting_queue',
            },
        ),
    ]
