# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oj',
            name='max_problem_id',
            field=models.IntegerField(default=0),
        ),
    ]
