# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_auto_20160808_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='origin_url',
            field=models.CharField(default='django-you', max_length=50, verbose_name='源url'),
        ),
    ]
